# Generated by Django 3.2.25 on 2024-03-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_Number', models.CharField(max_length=50)),
                ('Class_Number', models.CharField(max_length=50)),
            ],
        ),
    ]
