# Generated by Django 5.0.4 on 2024-04-13 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stu_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Stu_Number", models.CharField(max_length=50)),
                ("Medu", models.IntegerField()),
                ("Fedu", models.IntegerField()),
                ("traveltime", models.IntegerField()),
                ("studytime", models.IntegerField()),
                ("failures", models.IntegerField()),
                ("famrel", models.IntegerField()),
                ("freetime", models.IntegerField()),
                ("goout", models.IntegerField()),
                ("healths", models.IntegerField()),
                ("absences", models.IntegerField()),
                ("G1", models.IntegerField()),
                ("G2", models.IntegerField()),
                ("G3", models.IntegerField()),
                (
                    "Class_Number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.classes",
                    ),
                ),
            ],
        ),
    ]
