# Generated by Django 5.0.4 on 2024-04-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stu_info",
            name="G1",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stu_info",
            name="G2",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
