# Generated by Django 5.0.4 on 2024-04-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                ("test_time", models.DateTimeField(primary_key=True, serialize=False)),
                ("avg_grade", models.FloatField()),
            ],
        ),
    ]
